// Patch 5/5 — Annuaire (v2) : composant AnnuaireView restructuré —
// bandeau "Accès rapide" fixe en haut (3-4 numéros directs), onglets
// "Agents" / "UO" en dessous ("Encadrants" renommé en "UO").
// Usage : node patch_annuaire_5_appjsx_view.js
// À exécuter depuis : C:\Users\olive\Desktop\f2p-pmp
// IMPORTANT : exécuter ce patch APRÈS patch_annuaire_4_appjsx_profil.js
// Si tu avais déjà appliqué l'ancienne version (v1, avec "Encadrants" en
// tuile/carte), pars d'un App.jsx propre (celui d'avant tout patch Annuaire)
// avant d'appliquer patch_4 puis ce patch_5 v2.

const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, 'src', 'App.jsx');
const NL = '\r\n';

function mustReplaceOnce(content, oldStr, newStr, label) {
  const count = content.split(oldStr).length - 1;
  if (count === 0) throw new Error(`[${label}] Ancre introuvable dans ${FILE}`);
  if (count > 1) throw new Error(`[${label}] Ancre trouvée ${count} fois (doit être unique) dans ${FILE}`);
  return content.replace(oldStr, newStr);
}

let content = fs.readFileSync(FILE).toString('utf-8');

// ── 1. Insertion du composant AnnuaireView (+ sous-composants) avant ImportDeroulement ──
const anchorImport = 'function ImportDeroulement({agent,onClose,onImport';

const composant = [
  'function AnnuaireView({currentAgent,isAdmin}){',
  '  const [recherche,setRecherche]=useState("");',
  '  const [accesRapide,setAccesRapide]=useState([]);',
  '  const [uo,setUo]=useState([]);',
  '  const [agentsAnnuaire,setAgentsAnnuaire]=useState([]);',
  '  const [loading,setLoading]=useState(true);',
  '  const [activeTab,setActiveTab]=useState("agents");',
  '  const [gererAcces,setGererAcces]=useState(false);',
  '  const [editAccesId,setEditAccesId]=useState(null);',
  '  const [nouvelAcces,setNouvelAcces]=useState(false);',
  '  const [editUoId,setEditUoId]=useState(null);',
  '  const [nouvelUo,setNouvelUo]=useState(false);',
  '',
  '  const recharger=()=>{',
  '    setLoading(true);',
  '    Promise.all([',
  '      api.annuaire.getAccesRapide().catch(()=>[]),',
  '      api.annuaire.getUo().catch(()=>[]),',
  '      api.annuaire.getAgents().catch(()=>[]),',
  '    ]).then(([acces,uoRows,agts])=>{',
  '      setAccesRapide(acces||[]);',
  '      setUo(uoRows||[]);',
  '      setAgentsAnnuaire(agts||[]);',
  '      setLoading(false);',
  '    });',
  '  };',
  '  useEffect(()=>{ recharger(); },[]);',
  '',
  '  const q=recherche.trim().toLowerCase();',
  '  const filtreAgents=agentsAnnuaire.filter(a=>!q||`${a.nom} ${a.prenom}`.toLowerCase().includes(q));',
  '  const filtreUo=uo.filter(u=>!q||`${u.fonction} ${u.titulaire_nom||""} ${u.titulaire_prenom||""}`.toLowerCase().includes(q));',
  '',
  '  if(loading)return(<div style={{textAlign:"center",padding:"60px 20px",color:"#94a3b8"}}>Chargement de l\'annuaire…</div>);',
  '',
  '  return(<div style={{display:"flex",flexDirection:"column",gap:16,maxWidth:640,margin:"0 auto"}}>',
  '',
  '    <div>',
  '      <div style={{fontSize:11,fontWeight:700,letterSpacing:"0.04em",textTransform:"uppercase",color:"#94a3b8",marginBottom:8,paddingLeft:2}}>Accès rapide</div>',
  '      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(78px,1fr))",gap:8}}>',
  '        {accesRapide.map(a=>(',
  '          <a key={a.id} href={`tel:${a.numero}`} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:5,padding:"10px 4px",borderRadius:12,border:"1.5px solid #e2e8f0",background:"#fff",textDecoration:"none"}}>',
  '            <div style={{width:36,height:36,borderRadius:"50%",background:"#D85A30",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16}}>📞</div>',
  '            <span style={{fontSize:11,fontWeight:600,textAlign:"center",lineHeight:1.2,color:"#1e293b"}}>{a.libelle}</span>',
  '          </a>',
  '        ))}',
  '        <button onClick={()=>{setGererAcces(true);setNouvelAcces(true);}} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:5,padding:"10px 4px",borderRadius:12,border:"1.5px dashed #cbd5e1",background:"transparent",cursor:"pointer"}}>',
  '          <div style={{width:36,height:36,borderRadius:"50%",border:"1.5px dashed #cbd5e1",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,color:"#94a3b8"}}>+</div>',
  '          <span style={{fontSize:11,fontWeight:600,color:"#94a3b8"}}>Ajouter</span>',
  '        </button>',
  '      </div>',
  '      {!gererAcces&&accesRapide.length>0&&',
  '        <button onClick={()=>setGererAcces(true)} style={{border:"none",background:"none",color:"#0C447C",fontWeight:600,fontSize:12,cursor:"pointer",marginTop:8,padding:0}}>Gérer les numéros</button>}',
  '      {gererAcces&&<div style={{marginTop:10,padding:12,borderRadius:12,border:"1.5px solid #e2e8f0",background:"#f8fafc"}}>',
  '        {nouvelAcces&&<AccesRapideForm onCancel={()=>setNouvelAcces(false)} onSaved={()=>{setNouvelAcces(false);recharger();}}/>}',
  '        {accesRapide.map(a=>editAccesId===a.id',
  '          ? <AccesRapideForm key={a.id} initial={a} onCancel={()=>setEditAccesId(null)} onSaved={()=>{setEditAccesId(null);recharger();}} onDelete={()=>{api.annuaire.deleteAccesRapide(a.id).then(recharger);}}/>',
  '          : <div key={a.id} style={{display:"flex",alignItems:"center",gap:10,padding:"7px 0",borderBottom:"1px solid #e2e8f0"}}>',
  '              <div style={{flex:1}}>',
  '                <div style={{fontWeight:600,fontSize:13,color:"#1e293b"}}>{a.libelle}</div>',
  '                <div style={{fontSize:12,color:"#64748b"}}>{a.numero}</div>',
  '              </div>',
  '              <button onClick={()=>setEditAccesId(a.id)} style={{border:"none",background:"none",cursor:"pointer",fontSize:14,color:"#94a3b8"}}>✎</button>',
  '            </div>',
  '        )}',
  '        <button onClick={()=>setGererAcces(false)} style={{border:"none",background:"none",color:"#64748b",fontWeight:600,fontSize:12,cursor:"pointer",marginTop:8,padding:0}}>Fermer</button>',
  '      </div>}',
  '    </div>',
  '',
  '    <div style={{height:1,background:"#e2e8f0"}}/>',
  '',
  '    <input placeholder="Rechercher un nom, une fonction…" value={recherche} onChange={e=>setRecherche(e.target.value)}',
  '      style={{padding:"11px 14px",border:"1.5px solid #e2e8f0",borderRadius:12,fontSize:14}}/>',
  '',
  '    <div style={{display:"flex",gap:6}}>',
  '      <button onClick={()=>setActiveTab("agents")} style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",gap:6,padding:"9px 0",borderRadius:10,fontSize:13,fontWeight:700,cursor:"pointer",',
  '        border:activeTab==="agents"?"1.5px solid #0C447C":"1.5px solid #e2e8f0",background:activeTab==="agents"?"#eff6ff":"#fff",color:"#1e293b"}}>',
  '        <span style={{width:7,height:7,borderRadius:"50%",background:"#378ADD"}}/>Agents',
  '      </button>',
  '      <button onClick={()=>setActiveTab("uo")} style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",gap:6,padding:"9px 0",borderRadius:10,fontSize:13,fontWeight:700,cursor:"pointer",',
  '        border:activeTab==="uo"?"1.5px solid #0C447C":"1.5px solid #e2e8f0",background:activeTab==="uo"?"#eff6ff":"#fff",color:"#1e293b"}}>',
  '        <span style={{width:7,height:7,borderRadius:"50%",background:"#1D9E75"}}/>UO',
  '      </button>',
  '    </div>',
  '',
  '    {activeTab==="agents"&&<div style={{background:"#fff",border:"1.5px solid #e2e8f0",borderRadius:14,padding:18}}>',
  '      <div style={{display:"flex",flexDirection:"column",gap:2}}>',
  '        {filtreAgents.map(a=>(',
  '          <div key={a.cp} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:"1px solid #f1f5f9"}}>',
  '            <div style={{flex:1,minWidth:0}}>',
  '              <div style={{fontWeight:600,fontSize:13,color:"#1e293b"}}>{a.prenom} {a.nom}</div>',
  '              <div style={{fontSize:11,color:"#94a3b8"}}>{a.grade||""}</div>',
  '            </div>',
  '            {a.telephone',
  '              ? <>',
  '                  <a href={`tel:${a.telephone}`} style={{textDecoration:"none",fontSize:18}} title="Appeler">📞</a>',
  '                  <a href={`sms:${a.telephone}`} style={{textDecoration:"none",fontSize:18}} title="SMS">💬</a>',
  '                </>',
  '              : <span style={{fontSize:12,color:"#cbd5e1"}}>Non communiqué</span>}',
  '          </div>',
  '        ))}',
  '        {filtreAgents.length===0&&<div style={{fontSize:13,color:"#94a3b8"}}>Aucun agent trouvé.</div>}',
  '      </div>',
  '    </div>}',
  '',
  '    {activeTab==="uo"&&<div style={{background:"#fff",border:"1.5px solid #e2e8f0",borderRadius:14,padding:18}}>',
  '      <div style={{display:"flex",justifyContent:"flex-end",marginBottom:10}}>',
  '        <button onClick={()=>setNouvelUo(true)} style={{display:"flex",alignItems:"center",gap:5,border:"none",background:"none",color:"#0C447C",fontWeight:700,fontSize:13,cursor:"pointer"}}>+ Ajouter un poste</button>',
  '      </div>',
  '      {nouvelUo&&<UoForm onCancel={()=>setNouvelUo(false)} onSaved={()=>{setNouvelUo(false);recharger();}}/>}',
  '      {filtreUo.length===0&&!nouvelUo&&<div style={{fontSize:13,color:"#94a3b8"}}>Aucun poste UO pour l\'instant.</div>}',
  '      <div style={{display:"flex",flexDirection:"column",gap:10}}>',
  '        {filtreUo.map(u=>editUoId===u.id',
  '          ? <UoForm key={u.id} initial={u} onCancel={()=>setEditUoId(null)} onSaved={()=>{setEditUoId(null);recharger();}} onDelete={()=>{api.annuaire.deleteUo(u.id).then(recharger);}}/>',
  '          : <div key={u.id} style={{padding:"10px 0",borderBottom:"1px solid #f1f5f9"}}>',
  '              <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}>',
  '                <div>',
  '                  <div style={{fontWeight:700,fontSize:13,color:"#1e293b"}}>{u.fonction}</div>',
  '                  <div style={{fontSize:12,color:"#64748b"}}>{(u.titulaire_prenom||u.titulaire_nom)?`${u.titulaire_prenom||""} ${u.titulaire_nom||""}`.trim():<span style={{color:"#cbd5e1"}}>Titulaire non communiqué</span>}</div>',
  '                </div>',
  '                <button onClick={()=>setEditUoId(u.id)} style={{border:"none",background:"none",cursor:"pointer",fontSize:14,color:"#94a3b8"}}>✎</button>',
  '              </div>',
  '              <div style={{display:"flex",flexWrap:"wrap",gap:12,marginTop:6}}>',
  '                <ContactLigne label="Mobile pro" valeur={u.mobile_pro}/>',
  '                <ContactLigne label="Mobile perso" valeur={u.mobile_perso}/>',
  '                <ContactLigne label="Fixe" valeur={u.fixe}/>',
  '                {u.email&&<a href={`mailto:${u.email}`} style={{fontSize:12,color:"#0C447C",textDecoration:"none"}}>✉️ {u.email}</a>}',
  '              </div>',
  '            </div>',
  '        )}',
  '      </div>',
  '    </div>}',
  '  </div>);',
  '}',
  '',
  'function ContactLigne({label,valeur}){',
  '  if(!valeur)return null;',
  '  return(<a href={`tel:${valeur}`} style={{fontSize:12,color:"#0C447C",textDecoration:"none"}}>{label==="Fixe"?"☎️":"📱"} {valeur}</a>);',
  '}',
  '',
  'function AccesRapideForm({initial,onCancel,onSaved,onDelete}){',
  '  const [libelle,setLibelle]=useState(initial?.libelle||"");',
  '  const [numero,setNumero]=useState(initial?.numero||"");',
  '  const [busy,setBusy]=useState(false);',
  '  const [err,setErr]=useState(null);',
  '  const valider=async()=>{',
  '    if(!libelle.trim()||!numero.trim()){setErr("Libellé et numéro obligatoires");return;}',
  '    setBusy(true);setErr(null);',
  '    try{',
  '      if(initial) await api.annuaire.updateAccesRapide(initial.id,{libelle,numero});',
  '      else await api.annuaire.createAccesRapide({libelle,numero});',
  '      onSaved();',
  '    }catch(e){setErr(e.message||"Erreur");}',
  '    setBusy(false);',
  '  };',
  '  return(<div style={{display:"flex",flexDirection:"column",gap:8,padding:"10px 0",borderBottom:"1px solid #e2e8f0"}}>',
  '    <input placeholder="Libellé (ex: Astreinte PRCI)" value={libelle} onChange={e=>setLibelle(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    <input placeholder="Numéro" value={numero} onChange={e=>setNumero(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    {err&&<div style={{fontSize:12,color:"#991b1b"}}>{err}</div>}',
  '    <div style={{display:"flex",gap:8}}>',
  '      <button onClick={valider} disabled={busy} style={{flex:1,padding:"9px 0",border:"none",borderRadius:9,fontWeight:700,fontSize:13,cursor:"pointer",background:"#0C447C",color:"#fff"}}>{busy?"…":"Enregistrer"}</button>',
  '      <button onClick={onCancel} style={{padding:"9px 14px",border:"1.5px solid #e2e8f0",borderRadius:9,fontWeight:600,fontSize:13,cursor:"pointer",background:"#fff",color:"#64748b"}}>Annuler</button>',
  '      {initial&&onDelete&&<button onClick={onDelete} style={{padding:"9px 14px",border:"none",borderRadius:9,fontWeight:600,fontSize:13,cursor:"pointer",background:"#fee2e2",color:"#991b1b"}}>Suppr.</button>}',
  '    </div>',
  '  </div>);',
  '}',
  '',
  'function UoForm({initial,onCancel,onSaved,onDelete}){',
  '  const [fonction,setFonction]=useState(initial?.fonction||"");',
  '  const [titulaireNom,setTitulaireNom]=useState(initial?.titulaire_nom||"");',
  '  const [titulairePrenom,setTitulairePrenom]=useState(initial?.titulaire_prenom||"");',
  '  const [mobilePro,setMobilePro]=useState(initial?.mobile_pro||"");',
  '  const [mobilePerso,setMobilePerso]=useState(initial?.mobile_perso||"");',
  '  const [fixe,setFixe]=useState(initial?.fixe||"");',
  '  const [email,setEmail]=useState(initial?.email||"");',
  '  const [busy,setBusy]=useState(false);',
  '  const [err,setErr]=useState(null);',
  '  const valider=async()=>{',
  '    if(!fonction.trim()){setErr("Le poste/fonction est obligatoire");return;}',
  '    setBusy(true);setErr(null);',
  '    const data={fonction,titulaire_nom:titulaireNom,titulaire_prenom:titulairePrenom,mobile_pro:mobilePro,mobile_perso:mobilePerso,fixe,email};',
  '    try{',
  '      if(initial) await api.annuaire.updateUo(initial.id,data);',
  '      else await api.annuaire.createUo(data);',
  '      onSaved();',
  '    }catch(e){setErr(e.message||"Erreur");}',
  '    setBusy(false);',
  '  };',
  '  return(<div style={{display:"flex",flexDirection:"column",gap:8,padding:"10px 0",borderBottom:"1px solid #f1f5f9"}}>',
  '    <input placeholder="Poste / fonction (ex: Assistant RH)" value={fonction} onChange={e=>setFonction(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    <div style={{display:"flex",gap:8}}>',
  '      <input placeholder="Prénom titulaire" value={titulairePrenom} onChange={e=>setTitulairePrenom(e.target.value)}',
  '        style={{flex:1,padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '      <input placeholder="Nom titulaire" value={titulaireNom} onChange={e=>setTitulaireNom(e.target.value)}',
  '        style={{flex:1,padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    </div>',
  '    <input placeholder="Mobile pro" value={mobilePro} onChange={e=>setMobilePro(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    <input placeholder="Mobile perso" value={mobilePerso} onChange={e=>setMobilePerso(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    <input placeholder="Fixe" value={fixe} onChange={e=>setFixe(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    <input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}',
  '      style={{padding:"9px 11px",border:"1.5px solid #e2e8f0",borderRadius:9,fontSize:13}}/>',
  '    {err&&<div style={{fontSize:12,color:"#991b1b"}}>{err}</div>}',
  '    <div style={{display:"flex",gap:8}}>',
  '      <button onClick={valider} disabled={busy} style={{flex:1,padding:"9px 0",border:"none",borderRadius:9,fontWeight:700,fontSize:13,cursor:"pointer",background:"#0C447C",color:"#fff"}}>{busy?"…":"Enregistrer"}</button>',
  '      <button onClick={onCancel} style={{padding:"9px 14px",border:"1.5px solid #e2e8f0",borderRadius:9,fontWeight:600,fontSize:13,cursor:"pointer",background:"#fff",color:"#64748b"}}>Annuler</button>',
  '      {initial&&onDelete&&<button onClick={onDelete} style={{padding:"9px 14px",border:"none",borderRadius:9,fontWeight:600,fontSize:13,cursor:"pointer",background:"#fee2e2",color:"#991b1b"}}>Suppr.</button>}',
  '    </div>',
  '  </div>);',
  '}',
  '',
  '',
].join(NL) + anchorImport;

content = mustReplaceOnce(content, anchorImport, composant, 'insert-annuaireview-component');

// ── 2. Ajout de l'entrée dans VIEWS ──
const oldViews = [
  '  const VIEWS=[',
  '    {k:"personal",l:"📊 Mon planning"},',
  '    {k:"global",  l:"📋 CPS Officiel"},',
  '    {k:"previsionnel", l:"\\u{1F4C5} Planning Prévisionnel"},',
  '    {k:"echanges",l:"🔄 Échanges"},',
  '    {k:"profil",  l:"👤 Mon profil"},',
  '    ...(isAdmin ? [{k:"admin", l:"\\u{1F451} Admin"}] : [])',
  '  ];',
].join(NL);

const newViews = [
  '  const VIEWS=[',
  '    {k:"personal",l:"📊 Mon planning"},',
  '    {k:"global",  l:"📋 CPS Officiel"},',
  '    {k:"previsionnel", l:"\\u{1F4C5} Planning Prévisionnel"},',
  '    {k:"echanges",l:"🔄 Échanges"},',
  '    {k:"annuaire",l:"📞 Annuaire"},',
  '    {k:"profil",  l:"👤 Mon profil"},',
  '    ...(isAdmin ? [{k:"admin", l:"\\u{1F451} Admin"}] : [])',
  '  ];',
].join(NL);

content = mustReplaceOnce(content, oldViews, newViews, 'add-view-entry');

// ── 3. Ajout dans le switch de contenu, juste après la vue Échanges ──
const oldSwitch = '  {view==="echanges"&&<EchangesView agents={agents} currentAgent={currentAgent||currentUser?.agent}/>}' + NL;
const newSwitch = oldSwitch + '  {view==="annuaire"&&<AnnuaireView currentAgent={currentAgent||currentUser?.agent} isAdmin={isAdmin}/>}' + NL;

content = mustReplaceOnce(content, oldSwitch, newSwitch, 'add-content-switch');

fs.writeFileSync(FILE, content, 'utf-8');
console.log('OK — App.jsx patché (AnnuaireView v2 : bandeau Accès rapide + onglets Agents/UO)');
