UPDATE agent SET poste='CCL' WHERE nom='BELLISSENT' AND prenom='Christophe';
UPDATE agent SET poste='CCL' WHERE nom='CHAHMI' AND prenom='Rochdi';
UPDATE agent SET poste='CCL' WHERE nom='BEFFARAL' AND prenom='Olivier';
UPDATE agent SET poste='CCL' WHERE nom='COIRRE' AND prenom='Yannick';
UPDATE agent SET poste='CCL' WHERE nom='EL ADRAOUI' AND prenom='Mounir';
UPDATE agent SET poste='Adj CCL' WHERE nom='HUTIN' AND prenom='Thomas';
UPDATE agent SET poste='Adj CCL' WHERE nom='FAROUIL' AND prenom='Cameron';
UPDATE agent SET poste='Adj CCL' WHERE nom='MILLERAND' AND prenom='Thomas';
UPDATE agent SET poste='Adj CCL' WHERE nom='LOGEAIS' AND prenom='Leslie';
UPDATE agent SET poste='Adj CCL' WHERE nom='LAFRANCE' AND prenom='Cyril';
UPDATE agent SET poste='Adj CCL' WHERE nom='DUPUY' AND prenom='Victorien';
UPDATE agent SET poste='Adj CCL' WHERE nom='BOLZER' AND prenom='Charles';
UPDATE agent SET poste='Adj CCL' WHERE nom='MIGNOT' AND prenom='Olivier';
UPDATE agent SET poste='AC LC' WHERE nom='MALY' AND prenom='Christophe';
UPDATE agent SET poste='AC LC' WHERE nom='BENNEQUIN' AND prenom='Benjamin';
UPDATE agent SET poste='AC LC' WHERE nom='FAIAD' AND prenom='Zoé';
UPDATE agent SET poste='AC LC' WHERE nom='DRAME' AND prenom='Ibrahima';
UPDATE agent SET poste='AC LC' WHERE nom='RINDER-BOYER' AND prenom='Jérôme';
UPDATE agent SET poste='AC LC' WHERE nom='AKSSIRIOUN' AND prenom='Mohamed';
UPDATE agent SET poste='AC LNE' WHERE nom='ZANFI' AND prenom='Yassine';
UPDATE agent SET poste='AC LNE' WHERE nom='CHOUAIB' AND prenom='Wassim';
UPDATE agent SET poste='AC LNE' WHERE nom='AUDREN' AND prenom='Yvon';
UPDATE agent SET poste='AC LNE' WHERE nom='BATY' AND prenom='Audrey';
UPDATE agent SET poste='AC LNE' WHERE nom='CORDEAU' AND prenom='Maxime';
UPDATE agent SET poste='AC LNE' WHERE nom='MOUAOUED' AND prenom='Abdelkhalid';
UPDATE agent SET poste='AC LNO' WHERE nom='MENDY' AND prenom='Alexandre';
UPDATE agent SET poste='AC LNO' WHERE nom='JAN' AND prenom='Kevin';
UPDATE agent SET poste='AC LNO' WHERE nom='OUBRAHAM' AND prenom='Adel';
UPDATE agent SET poste='AC LNO' WHERE nom='MASUY' AND prenom='Thomas';
UPDATE agent SET poste='AC LNO' WHERE nom='SOUNALATH' AND prenom='Vythoune';
UPDATE agent SET poste='AC LNO' WHERE nom='CAILLET' AND prenom='Maxime';
UPDATE agent SET poste='AC VGD' WHERE nom='BOUHEND' AND prenom='Ryad';
UPDATE agent SET poste='AC VGD' WHERE nom='COSAQUE' AND prenom='Patrick';
UPDATE agent SET poste='AC VGD' WHERE nom='LUCAS' AND prenom='Samuel';
UPDATE agent SET poste='DPX PRCI' WHERE nom='BAILLON' AND prenom='Guillaume';
UPDATE agent SET poste='Adj DPX' WHERE nom='CAMPOY' AND prenom='Nicolas';
UPDATE agent SET poste='SD' WHERE nom='HAIDER' AND prenom='Zesheen';
UPDATE agent SET poste='Pauseur PA1' WHERE nom='VICENTE CARREIRA' AND prenom='Lucile';
UPDATE agent SET poste='Pauseur PA3' WHERE nom='AUDREN' AND prenom='Gildas';
UPDATE agent SET poste='Pauseur PA2' WHERE nom='BENDIKHA' AND prenom='Sofiane';
UPDATE agent SET poste='Pauseur PA2' WHERE nom='GUEGAIN' AND prenom='Magalie';
UPDATE agent SET poste='AFO PRCI' WHERE nom='BELOTTI' AND prenom='Florent';
UPDATE agent SET poste='AFO PRCI' WHERE nom='GUAY' AND prenom='Sébastien';
UPDATE agent SET poste='CAF' WHERE nom='KINET' AND prenom='Julien';
UPDATE agent SET poste='PPRCI' WHERE nom='ILIC-HERBIVO' AND prenom='Théo';
UPDATE agent SET poste='Disponible' WHERE nom='DAVOST' AND prenom='Antoine';
UPDATE agent SET poste='AC LNO' WHERE nom='TOUNKARA' AND prenom='El-Haj';
UPDATE agent SET poste='SD' WHERE nom='METELSKI' AND prenom='Kevin';
UPDATE agent SET poste='AC LC' WHERE nom='BECHTOLD' AND prenom='Romain';
UPDATE agent SET poste='AC LNE' WHERE nom='BOUHADJEB' AND prenom='Mohammed';
UPDATE agent SET poste='AC LNE' WHERE nom='AUDREN' AND prenom='Yvon';
UPDATE agent SET poste='AC LNO' WHERE nom='LE MOISY' AND prenom='Tom';
UPDATE agent SET poste='CCL' WHERE nom='KRAFFT' AND prenom='Eric';
UPDATE agent SET poste='AC PAR' WHERE nom='HUMEZ' AND prenom='Cindy';
UPDATE agent SET poste='AC PAR' WHERE nom='RACAMIER' AND prenom='Alexandre';
UPDATE agent SET poste='AC PAR' WHERE nom='MAILLET' AND prenom='Antoine';
UPDATE agent SET poste='AC PAR' WHERE nom='IMART' AND prenom='Pascal';
UPDATE agent SET poste='AC PAR' WHERE nom='MAGRINO' AND prenom='Enzo';
UPDATE agent SET poste='AC PAR' WHERE nom='VALES-TOLEDANO' AND prenom='Ava';
UPDATE agent SET poste='AC PAR' WHERE nom='BARBASTE' AND prenom='Thomas';
UPDATE agent SET poste='AC PAR' WHERE nom='LE MOISY' AND prenom='Tom';
UPDATE agent SET poste='AC PAR' WHERE nom='PASTANT' AND prenom='Maxime';
UPDATE agent SET poste='Aide AC PAR' WHERE nom='WAVELET' AND prenom='François';
UPDATE agent SET poste='Aide AC PAR' WHERE nom='CHENEVOTOT' AND prenom='Lionel';
UPDATE agent SET poste='Aide AC PAR' WHERE nom='USSON' AND prenom='Antoine';
UPDATE agent SET poste='Aide AC PAR' WHERE nom='SCHRAMM' AND prenom='Camille';
UPDATE agent SET poste='CT AC Travaux' WHERE nom='ILIC-HERBIVO' AND prenom='Théo';
UPDATE agent SET poste='CT AC Travaux' WHERE nom='MERCIER' AND prenom='Yoann';
UPDATE agent SET poste='DPX PAR' WHERE nom='LAMBERT' AND prenom='Olivier';
UPDATE agent SET poste='ASMTE PAR' WHERE nom='MILLES' AND prenom='Valérie';
UPDATE agent SET poste='AFO PAR' WHERE nom='AUREILLE' AND prenom='Baptiste';
UPDATE agent SET poste='AC PAR' WHERE nom='HUON' AND prenom='Grégoire';
UPDATE agent SET poste='Aide AC PAR' WHERE nom='MOREAU' AND prenom='Maxence';
UPDATE agent SET poste='AC PAR' WHERE nom='MICHEL' AND prenom='François';
UPDATE agent SET poste='DPX PAR' WHERE nom='BODIN' AND prenom='Julien';
UPDATE agent SET poste='AC PAR' WHERE nom='SAURY' AND prenom='Stéphane';
UPDATE agent SET poste='AC LC' WHERE nom='LEGOGUELIN' AND prenom='Antoine';
